### ISSUE TITLE
Different song than shown on the website

### ISSUE THREAD

**Issue by Lapahn** [patrickgalbraith/mapofmetal#1]
Hey!

Love your website, but I found out that at "Folk Metal" Trollhammeren - Finntroll shows the song "Solsagan" and Finntroll is written with two "n"

Just two little things that I saw when clicking through the website :)

**Comment by tardate** [comment]
Interesting how the videos are listed in data. I'm guessing it is to gloss over missing/blocked youtube clips(?).

This appears to be the setup for Trollhammeren:

    {
      "artist": "Fintroll",
      "title": "Trollhammeren",
      "year": "2004",
      "videos": [
        "yGywo81G6lk", # not available
        "mkVwA__Fk9g", # Solsagan
        "tEzuxkkGyWQ", # Under Bergets Rot 
        "d3u86DPd7qc", # Trollhammaren
        "DXKwVe1SBTA", # Trollhammaren
        "nYwFPaK6UQY", # Trollhammaren
        "FN3bKh8fKwQ"  # Trollhammeren
      ]
    },


So I presume a fix would looks like this - if I'm understanding how the data structure work..

    {
      "artist": "Finntroll",
      "title": "Trollhammeren",
      "year": "2004",
      "videos": [
        "d3u86DPd7qc",
        "DXKwVe1SBTA",
        "nYwFPaK6UQY",
        "FN3bKh8fKwQ" 
      ]
    },

@patrickgalbraith if this is the correct way to fix the problem, is it appropriate to submit a pull request with that change? (I'm not sure if the data in this repo is "master" or perhaps you are generating it from somewhere else first)

**Comment by patrickgalbraith** [comment]
Thanks for the feedback! 

I recently rewrote the site from flash and in doing so realised the playlists were filled with missing sources. To fix it I just reseeded them with a script which searches for the video on Youtube by track name and artist. Unfortunately this approach has lead to some incorrect data which will take time to fix so I really appreciate the help with it.

@tardate Yeah I have more than one source so that invalid videos can be skipped over. Feel free to submit a pull request. The data in this repository is the `master` and is what I use to generate the compiled version used on the site.
