### ISSUE TITLE
Project stalled ?

### ISSUE THREAD

**Issue by Brianmanden** [patrickgalbraith/mapofmetal#23]
Has this fine project stalled ?

It seems the most recent issue is from 2018 !

**Comment by patrickgalbraith** [comment]
Hi Brian,

The answer to that is kinda complicated.

The site was first built around 2009 in Flash which was unfortunately just around the time Steve Jobs struck a fatal blow to Flash by stating it would never be supported on iOS. At the time Flash wasn't a bad choice to build something interactive like this site, as doing so using JS was a lot more challenging since the web platform hadn't stabilized at that time and Internet Explorer was by far the most popular browser.

I rewrote it in HTML5 around 4 years ago (and open-sourced the project) in hopes that when Flash died the site would live on. In hindsight that was a good decision since the site would be dead now given that Flash was another victim of 2020 being killed off for good by Adobe in December.

I have done some prototyping of a mobile redesign as well as a larger map incorporating years after 2010 (and even other genres outside of metal like punk etc...) as well as reworking the UI to be more interactive (think pseudo-3D) but I've never been happy with the outcome or it was too ambitious and I haven't had the time and motivation to finish it.

So has the project stalled? Kinda but the point of all that I've written above is that the project goes through spurts of development which happen from time to time. I have dreams of a much bigger and better version of the site, if or when that version will ever be realised I cannot say.

**Comment by Brianmanden** [comment]
Hi Patrick,

Thank you for the explanation - it makes sense :)

I would like to see the new UI and redesign - can I find it online somewhere ?

I am thinking about finding a project to contribute to and for a metalhead like me - Map Of Metal would be a great project !

#RockOn, stay mædl \m/\m/

**Comment by patrickgalbraith** [comment]
@Brianmanden I don't have anything online for that.

I tried to find the mobile concepts I did but can't find the files. But the idea was pretty simple, the main issue is that the video player must be displayed when music is playing (this is required by Google/Youtube T&Cs). So that probably means turning off the video when navigating the map. 

Other than that if you want to contribute I'd be more than happy to have some help with the site.

**Comment by Brianmanden** [comment]
Hi @patrickgalbraith 

Sorry for the late response. 

I am still interested in contributing. I have tried cloning the repository down locally to my machine and I started fiddling around with the code to getting it to run. As I remember it there were some problems with one of the dependencies - openseadragon.

GitHub has a new feature - a repository can be edited and run on gitpod.io - [https://imgur.com/a/gXtkXfw](https://imgur.com/a/gXtkXfw)

My suggestion is we look into fixing the problems with dependencies - secondly getting the project running on Gitpod.
That way the entry barrier is lower for developers to start contributing.

Your thoughts ?

**Comment by patrickgalbraith** [comment]
@Brianmanden I used a forked version because there was an issue with the library. That issue has since been resolved so we should be fine to use the official version from https://www.npmjs.com/package/openseadragon now.

However it looks like gulp needs to be updated since v3 doesn't run under new version of node so I'll have a look at getting a running version in the next day or so.

**Comment by Brianmanden** [comment]
@patrickgalbraith That sounds great. I´ll keep an eye on this thread.

Let´s get this rolling again :)

**Comment by patrickgalbraith** [comment]
@Brianmanden I have pushed a new version.

- Upgraded react/redux etc.. to latest version, and fixed issues after upgrade
- Replace gulp/webpack/babel with parcel, this simplifies the build process a lot an allows the project to work on newer version of NodeJS
- Converted types from flow to typescript

**Comment by Brianmanden** [comment]
@patrickgalbraith, Great .. 

I´m npm installing at the moment and will look into the code today.

Further communication through https://twitter.com/P_Galbraith / https://twitter.com/mapofmetal ?

**Comment by patrickgalbraith** [comment]
@Brianmanden I've created a discord to discuss the project here https://discord.gg/yW2wrPT7ZE
